"""SentraX AI — Shared Data Schemas and Validation Models.

Reference: Docs/Agents.md & Docs/architecture.md
"""

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field


# --- Recon Agent Schemas ---

class FormInfo(BaseModel):
    """HTML form structure extracted during DAST recon."""
    action: str
    method: str = "GET"
    fields: List[str] = Field(default_factory=list)


class PageInfo(BaseModel):
    """Page attack surface mapping extracted during DAST recon."""
    url: str
    forms: List[FormInfo] = Field(default_factory=list)
    endpoints_observed: List[str] = Field(default_factory=list)


class ReconURLResult(BaseModel):
    """Full DAST Recon Agent JSON output."""
    mode: Literal["url"] = "url"
    target: str
    pages: List[PageInfo] = Field(default_factory=list)


class SASTFindingRaw(BaseModel):
    """Raw pattern match from SAST folder recon."""
    file: str
    line: int
    pattern: str
    snippet: str


class ReconFolderResult(BaseModel):
    """Full SAST Recon Agent JSON output."""
    mode: Literal["folder"] = "folder"
    target: str
    findings_raw: List[SASTFindingRaw] = Field(default_factory=list)


# --- Strategist Agent Schemas ---

class StrategistTask(BaseModel):
    """Individual testing task planned by Strategist Agent."""
    id: str
    target: str
    vuln_type: Literal["sqli", "xss", "idor", "broken_auth"]
    reasoning: str


class StrategistResult(BaseModel):
    """Prioritized test plan output by Strategist Agent."""
    tasks: List[StrategistTask] = Field(default_factory=list)


# --- Exploit Agent Schemas ---

class FindingEvidence(BaseModel):
    """Deterministic proof of vulnerability."""
    request_sent: str
    response_snippet: str
    why_confirmed: str


class ConfirmedFinding(BaseModel):
    """Finding proven vulnerable by Exploit Agent."""
    finding_id: str
    vuln_type: Literal["sqli", "xss", "idor", "broken_auth"]
    target: str
    mode: Literal["dast", "sast"]
    confirmed: bool = True
    evidence: FindingEvidence
    severity: Literal["high", "medium", "low", "critical"] = "high"


# --- Remediation Agent Schemas ---

class RemediationFix(BaseModel):
    """Actionable fix suggestion generated by Remediation Agent."""
    finding_id: str
    original_snippet: str
    fixed_snippet: str
    explanation: str


# --- Reporter Agent Schemas ---

class ScanReportSummary(BaseModel):
    """High-level summary of scan results."""
    total_findings: int
    high_count: int
    medium_count: int
    low_count: int


class EnrichedFinding(BaseModel):
    """Confirmed finding combined with its remediation fix."""
    finding: ConfirmedFinding
    remediation: Optional[RemediationFix] = None


class FinalScanReport(BaseModel):
    """Complete deliverable scan report."""
    target: str
    mode: Literal["dast", "sast"]
    timestamp: str
    summary: ScanReportSummary
    findings: List[EnrichedFinding]
    markdown_path: Optional[str] = None
